#!/bin/bash

#		Name:    finddep_strace
#		Version: 1
#		Licence: GPL v.3
#       https://gnu.org/licenses/gpl.html



#	This script parse output from:
#   	$ strace -e open photoqt 2>&1 | grep -v "No such"  
# 	to get links and save dependencies rpm list to "list packages" file
#		Script made for PCLinuxOS


#	How Use:
#			./finddep_strace name_file


#	Example output:  "list_packages" file
#
#		lib64qt5opengl5-5.4.2-1pclos2015
#		lib64qt5qml5-5.4.2-1pclos2015
#		lib64qt5quick5-5.4.2-1pclos2015
#		lib64qt5sql5-5.4.2-1pclos2015
#		lib64qt5widgets5-5.4.2-1pclos2015
#		lib64qtgui4-4.8.7-1pclos2015
#		lib64qtsvg5-5.4.2-1pclos2015

#======================================================================================




#  check - if file exist then remove it
    rm  link1
    rm  list_packages







# info
echo $1


# parsing
cat $1 | cut -d "\"" -f2 | sort | uniq > link1


# info
echo "$1 parsed"




# In file links is $aa lines.
aa=$(cat link1 | wc -l)
echo $aa



# for i in `seq 1 $aa`
for i in `seq 1 $aa`
do
		# info
		echo "$i / $aa"

		# line from lista_elf
		ab=$(awk 'NR=='$i link1)

		rpm -qf $ab >> list_packages

 done


# uniq
ac=$(cat list_packages | sort | uniq)
echo "$ac" > list_packages
ad=$(cat list_packages | wc -l)

# info
echo $aa
echo $ad
echo "Ready."

